# config/application.yml
defaults: &defaults

development:
  <<: *defaults
  social_login:
    facebook:
      app_id: 498017087062782
      app_secret: "c3c3751a02062746b90a57d70b6fd48c"
    twitter:
      app_id: "VlabV7s7myjIbHhncDS79yDRE"
      app_secret: "G45dGVaeUYYfO2DWvNMLBIPltpFJr3TTdWDnHdBMZ2Sn4yXo0C"

test:
  <<: *defaults
  social_login:
    facebook:
      app_id: 498017087062782
      app_secret: "c3c3751a02062746b90a57d70b6fd48c"
    twitter:
      app_id: "VlabV7s7myjIbHhncDS79yDRE"
      app_secret: "G45dGVaeUYYfO2DWvNMLBIPltpFJr3TTdWDnHdBMZ2Sn4yXo0C"

production:
  <<: *defaults
  social_login:
    facebook:
      app_id: 498016547062836
      app_secret: "6e830483818971f7fae2d4506ff20a02"
    twitter:
      app_id: "3w6tmpWnlTRNawq0VqYTo3n1x"
      app_secret: "e1xso5EnLC8L3yxoeROANMNn8RCllhpc8FtvjdsqudpVTfb0eH"
