production:
  solr:
    hostname: aws-virginia-solr4-10.opensolr.com
    port: 443
    path: /solr/reward_system
    log_level: WARNING

development:
  solr:
    hostname: localhost
    port: 8982
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: localhost
    port: 8981
    log_level: WARNING
    path: /solr/test
